---
name: "Build and push image to ghcr.io"
on:
  push:
    tags: 
     - '*'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    strategy:
      fail-fast: false
      matrix:
        system:
          - aarch64-linux
          - x86_64-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          enable_kvm: true
          extra_nix_config: |
            extra-platforms = aarch64-linux
      - name: Log into ghcr
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          nix build --option sandbox true .#dockerImage.${{ matrix.system }}
          docker image load --input result
          docker image tag shorturl:latest ${{ env.REGISTRY }}/fkouhai/shorturl-${{ matrix.system }}:${{ github.ref_name }}
          docker image ls
          docker push ${{ env.REGISTRY }}/fkouhai/shorturl-${{ matrix.system }}:${{ github.ref_name }}
